// <auto-generated />
using System;
using KiltaSphereAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KiltaSphereAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251201091406_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KiltaSphereAPI.Models.CommunicationLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("CommunicationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.HasIndex("MemberId");

                    b.ToTable("CommunicationLogs");
                });

            modelBuilder.Entity("KiltaSphereAPI.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalIdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            Email = "aino.m@example.fi",
                            FirstName = "Aino",
                            JoiningDate = new DateTime(2020, 12, 1, 11, 14, 5, 244, DateTimeKind.Local).AddTicks(9174),
                            LastName = "Mäkinen",
                            MembershipStatus = "Active"
                        },
                        new
                        {
                            MemberId = 2,
                            Email = "elias.v@example.fi",
                            FirstName = "Elias",
                            JoiningDate = new DateTime(2024, 12, 1, 11, 14, 5, 244, DateTimeKind.Local).AddTicks(9184),
                            LastName = "Virtanen",
                            MembershipStatus = "Pending"
                        },
                        new
                        {
                            MemberId = 3,
                            Email = "sofi.k@example.fi",
                            FirstName = "Sofi",
                            JoiningDate = new DateTime(2025, 9, 1, 11, 14, 5, 244, DateTimeKind.Local).AddTicks(9188),
                            LastName = "Korhonen",
                            MembershipStatus = "Active"
                        });
                });

            modelBuilder.Entity("KiltaSphereAPI.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentId");

                    b.HasIndex("MemberId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("KiltaSphereAPI.Models.CommunicationLog", b =>
                {
                    b.HasOne("KiltaSphereAPI.Models.Member", "Member")
                        .WithMany("CommunicationLogs")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("KiltaSphereAPI.Models.Payment", b =>
                {
                    b.HasOne("KiltaSphereAPI.Models.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("KiltaSphereAPI.Models.Member", b =>
                {
                    b.Navigation("CommunicationLogs");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
